### ISSUE TITLE
AttributeError in runner.py When Handling Exceeded Context Length

### ISSUE THREAD

**Issue by Umpire2018** [LOGIC-10/RepoAgent#18]
**Description:**
Encountered an `AttributeError` in `runner.py` after multiple attempts to process a long code snippet using the `gpt-3.5-turbo-16k` model.

**Error Messages:**
Repeated errors indicating the model's maximum context length was exceeded:

```python
Error: The model's maximum context length is exceeded. Reducing the length of the messages. Attempt 1 of 5
...
Error: The model's maximum context length is exceeded. Reducing the length of the messages. Attempt 5 of 5
```

Followed by an `AttributeError`:
```python
   File "ai_doc\runner.py", line 341, in <module>
    runner.run()
  File "ai_doc\runner.py", line 165, in run
    self.process_file_changes(repo_path, file_path, is_new_file)
  File "ai_doc\runner.py", line 217, in process_file_changes
    json_data[file_handler.file_path] = self.update_existing_item(json_data[file_handler.file_path], file_handler, changes_in_pyfile)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ai_doc\runner.py", line 298, in update_existing_item
    future.result()
  File "Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ai_doc\runner.py", line 308, in update_object
    obj["md_content"] = response_message.content
                        ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'content'
```

**Suspected Issue:**
The `response_message` object is `None`, likely due to the previous errors where the model's maximum context length was exceeded. The code attempts to access the `content` attribute of a `NoneType` object, leading to the `AttributeError`.

**Suggested Solution:**
- Investigate why the model's maximum context length is being exceeded and attempt to reduce the input size accordingly.
- Implement a check to ensure `response_message` is not `None` before attempting to access its `content` attribute. This could prevent the `AttributeError` and provide a clearer indication of the underlying issue.

**Comment by LOGIC-10** [comment]
resolved， please try it on dev branch
