### ISSUE TITLE
chat with repo workflow issue

### ISSUE THREAD

**Issue by innovation64** [LOGIC-10/RepoAgent#25]
#### **核心概念**

- **目标**: 创建一个能够与代码仓库进行交互的聊天系统。
- **总结** : 根据用户的问题做匹配，匹配到对应的文档、代码、引用关系。然后将匹配到的结果送给大模型，让大模型去做思考，最后生成回答。
- **灵感来源**: LangChian 的 [RAG over code | 🦜️🔗 Langchain](https://js.langchain.com/docs/use_cases/rag/code_understanding)

#### **具体要求**

1. **动态更新文档chunks对应的向量**
   - **文档变更监控**: 由于MD文件内容可能会频繁变更，系统必须使用工具监控文档的更改，并相应地更新文档chunks的向量表示。
   - **向量存储与版本控制**: 必须有一个高效的向量存储系统来管理文档与其向量表示之间的一致性。

2. **组织文档和代码块**
   - **检索方法**: 进行embedding search，将用户查询转换成向量，再与向量数据库中的内容进行比较。基于相似度选择最相关的几个块进行返回，确保回答的准确性和相关性。

3. **代码整合**
   - **加入原始代码**: 文档对应的代码也应进行向量化处理，以便整合到检索过程中。
   - **多路召回**: 除了向量化处理外，还包括关键字检索等传统搜索方法，以及可能的语义搜索和模式匹配技术，以增强检索的全面性和准确度。

5. **处理引用关系**
   - **代码块引用关系**: 召回的代码块应包含其在项目中的具体位置信息，以及它与其他代码块或文档的引用关系。这有助于构建更加全面和连贯的上下文。（当前已实现）

6. **大模型的总结与回答**
   - **综合回答**: 大模型应该能够进行综合分析，理解复杂的代码和文档关系，并基于召回的内容形成对用户查询的综合回答。

**Comment by innovation64** [comment]
27th Dec

Waiting for completion

# Searching and summary

##

## technical route

```mermaid

graph TB
    Start(start) --> Open[question query]
    Open --> Put[RAG]
    Put[RAG] --> IsFit{LLM fit for logic}
    
    IsFit -->|LLM fit for logic| Close[Send to LLM with relevant information]
    Close --> End(output)
        
    IsFit -->|unfit| CloseB[No relevant infor]
   CloseB --> End2(NO solution)
```
## UML graph

# Explaination

>ps:





                                                                                                                                        developer: Yang Lee

**Comment by innovation64** [comment]
# RAG part
- langchain
- llamaindex

**Comment by OctoberFox11** [comment]
## 流程概览

1. **开始（Start）**
   - 流程的起始点，接收用户的问题或查询。

2. **问题查询（Open）**
   - 初步分析用户的问题。
   - 判断问题类型（如编程问题、数据查询、技术指导等）。

3. **使用RAG系统（Put[RAG]）**
   - RAG系统处理问题，确定是否存在已知的解决方案或相关信息。
   - 利用RAG系统的大规模文档检索能力来寻找可能的答案或信息。

4. **LLM适用性判断（IsFit）**
   - 判断问题是否适合用LLM（如GPT-4）逻辑处理。
   - 考虑问题的复杂性、具体性以及是否需要深入的逻辑推理。

5. **适用LLM逻辑处理（Close[发送相关信息至LLM]）**
   - 将问题和RAG系统找到的相关信息一起送至LLM处理。
   - LLM进行深入分析和处理，生成解决方案或答案。

6. **输出结果（End）**
   - 将LLM处理的结果呈现给用户。
   - 结果可能包括解决方案、建议或其他相关信息。

7. **不适用LLM逻辑处理（CloseB[没有相关信息]）**
   - 如果问题不适合用LLM逻辑处理，或RAG系统未找到相关信息。
   - 提供标准回复或引导用户寻找其他资源。

8. **无解决方案（End2）**
   - 通知用户此问题当前没有可行的解决方案。
   - 可能建议用户寻求其他渠道的帮助或等待进一步的研究。

**Comment by LOGIC-10** [comment]
> ## 流程概览
> 1. **开始（Start）**
>    
>    * 流程的起始点，接收用户的问题或查询。
> 2. **问题查询（Open）**
>    
>    * 初步分析用户的问题。
>    * 判断问题类型（如编程问题、数据查询、技术指导等）。
> 3. **使用RAG系统（Put[RAG]）**
>    
>    * RAG系统处理问题，确定是否存在已知的解决方案或相关信息。
>    * 使用向量数据库和字段精确搜索等多种手段综合检索
> 4. **LLM相关性判断（IsFit）**
>    
>    * 由LLM判断资料是否和Query相关
> 5. **适用LLM逻辑处理（Close[发送相关信息至LLM]）**
>    
>    * 将问题和RAG系统找到的相关信息一起送至LLM处理
>    * LLM生成解决方案或答案
> 6. **输出结果（End）**
> 7. **不适用LLM逻辑处理（CloseB[没有相关信息]）**
>    
>    * 提供标准无信息回复，或引导用户寻找其他资源
> 8. **无解决方案（End2）**
>    
>    * 通知用户此问题当前没有可行的解决方案
>    * 可能建议用户寻求其他渠道的帮助

LLM相关性判断（IsFit）这方面你的意思是把多路召回的结果都送给LLM但是不要它回答？而是给出一个相关性判断？

**Comment by Guo-Zhang** [comment]
1. Why Chroma? What is the advantage of it compared to others?
2. The "tech route" seems to be a standard RAG. What will be the difficulties?

**Comment by innovation64** [comment]
> 1. Why Chroma? What is the advantage of it compared to others?
> 2. The "tech route" seems to be a standard RAG. What will be the difficulties?

@LOGIC-10 @Guo-Zhang 
well , first for the Chroma. I don't think this is an important thing in this design system. that's not a big deal. whatever you choose Chroma,  pinecone or weaviate.   all of these are fine. so we just need a vector db, so never mind.

and second, frankly speaking, the tech route is just a draft based on my previous knowledge, i will correct it, i know it has a lot of problems, so I just list a formal one. based on what I searched, there are a lot of difficulties.


far from now, here is my summary source: 
https://innovation64.github.io/2023/12/27/RAG/

I need more time to get to know the repo and code tools,

base all of  the above things,that I maybe can design an initial draft chat with repo system

so please be patient, I'm doing more research on it and will give you guys a solution eventually

**Comment by innovation64** [comment]
Here is code part without rag sys Answer by GPT4

1. **Identify File Types**: Determine the types of files you want to process. This may include source code files (.py, .js, .java, etc.), configuration files (.xml, .json, .yml), documentation files (.md, .txt), and others.

2. **Access Repository Contents via GitHub API**: Use the GitHub API to access the contents of the repository. The key API endpoint to use is:
   
   - `GET /repos/{owner}/{repo}/contents/{path}`: This retrieves the contents of a specific path within the repository. If the path is a directory, it returns a list of all files and subdirectories within it.

3. **Recursively Traverse the Repository**: To get files from all directories in the repository, recursively traverse each directory. For each directory, use the API endpoint to retrieve its contents and download the relevant files.

4. **Download and Store Files**: Download the content of each identified file, which may require handling different file formats and possibly converting them to a uniform format for processing.

5. **Preprocess Files for LLM**: Depending on the file type and the intended processing, you might need to preprocess the files. For source code, this might include extracting comments or code snippets. For documentation, it might involve converting markdown or HTML to plain text.

6. **Feed Files into LLM**: Once preprocessed, feed the content into the Large Language Model. The LLM can be used for various tasks like code analysis, generating documentation, summarizing changes, etc.

7. **Process LLM Output**: Use the output from the LLM as needed, which could include generating insights, automating tasks, or further analyzing the content.

Remember to comply with GitHub's terms and API rate limits. Also, consider the computational resources and potential costs if processing a large number of files or performing complex analysis.

**Comment by LOGIC-10** [comment]
This analysis is really too superficial.

I think the 6 steps I mentioned in the meeting that night were very clear and specific, including the technical details and precautions for each item. I suggest that you ask @Umpire2018 for the recording files of the meeting, and then explore more possibilities and try different details based on my existing solution instead of starting from scratch. I believe this will greatly improve your efficiency.

**Comment by innovation64** [comment]
> This analysis is really too superficial.
> 
> I think the 6 steps I mentioned in the meeting that night were very clear and specific, including the technical details and precautions for each item. I suggest that you ask @Umpire2018 for the recording files of the meeting, and then explore more possibilities and try different details based on my existing solution instead of starting from scratch. I believe this will greatly improve your efficiency.

@LOGIC-10 
I know, I'm still designing a chat repo with rag sys, but not put it into issue. and I will check out the 6 steps you mentioned that night, to make sure that i would not lose something

**Comment by LOGIC-10** [comment]
That's great. Looking forward to your implementation in several days.

**Comment by Umpire2018** [comment]
> # RAG part
> - langchain
> - llamaindex(recommended)

👨‍👩‍👧‍👦 Who is LlamaIndex for?

LlamaIndex provides tools for beginners, advanced users, and everyone in between.

Our high-level API allows beginner users to use LlamaIndex to ingest and query their data in 5 lines of code.

For more complex applications, our lower-level APIs allow advanced users to customize and extend any module—data connectors, indices, retrievers, query engines, reranking modules—to fit their needs.

@innovation64 个人认为对 RAG 系统提出的讨论已经足够，接下来就可以使用现成的框架去进行开发了。目前看来使用 llamaindex , Chroma 是比较好的选择。Let's do it!

那么你对此问题的分工有什么见解？比如说是否你先来开始，后续有什么需要我去做的你再指派给我？

**Comment by innovation64** [comment]
> > # RAG part
> > 
> > * langchain
> > * llamaindex(recommended)
> 
> 👨‍👩‍👧‍👦 Who is LlamaIndex for?
> 
> LlamaIndex provides tools for beginners, advanced users, and everyone in between.
> 
> Our high-level API allows beginner users to use LlamaIndex to ingest and query their data in 5 lines of code.
> 
> For more complex applications, our lower-level APIs allow advanced users to customize and extend any module—data connectors, indices, retrievers, query engines, reranking modules—to fit their needs.
> 
> @innovation64 个人认为对 RAG 系统提出的讨论已经足够，接下来就可以使用现成的框架去进行开发了。目前看来使用 llamaindex , Chroma 是比较好的选择。Let's do it!
> 
> 那么你对此问题的分工有什么见解？比如说是否你先来开始，后续有什么需要我去做的你再指派给我？

ok,i will try it first

**Comment by innovation64** [comment]
目前进度，用gradio搭建基本的chatbot完毕
目前功能
- 多轮对话
- gradio UI
- 目前只使用openai API 没有增加rag

RAG部分
- 基本流程运行出现OOD
>默认的llamaindex的嵌入模型生成repo的index会显存益处（我电脑没啥显存），尝试小数据处理解决bug中

**Comment by Umpire2018** [comment]
> 用gradio搭建基本的chatbot完毕

也许可以先从命令行 Chat 开始，之后再考虑前端的事情。

**Comment by innovation64** [comment]
目前进度
- 基本的gradio 交互页面已完成
- 基本的rag pipeline已完成
- 尚未接入向量数据库,正在完善本地保存讲，json化向量接入数据库
- 正在进行对于代码chunck，[目前参考](https://docs.sweep.dev/blogs/chunking-2m-files)
- 目前代码较乱还没有封装整合暂时不宜PR

**Comment by LOGIC-10** [comment]
🚀cool，你可以创建一个分支chat_with_repo，我们可以看着分支进行参考和下一步讨论，这样会更清晰。

**Comment by innovation64** [comment]
目前进度 January 4th
- 完成基本交互界面
- 完成基本多轮对话界面
- 完成Automering 检索算法的 RAG
- 完成数据库存储

剩余任务
- 前置query的规范
- 数据库更新触发机制
- 代码文件chunk单独分类与合并树节点向量化

**Comment by Umpire2018** [comment]
Finished in #32 .
